version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    privileged: true
    tty: true
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/
      - ./html:/usr/share/nginx/html
      - ./openssl/:/etc/nginx/cert
    ports:
      - "81:80"
      - "8080:8080"
      - "443:443"
